export validationToken=olin_loanbot
export serverURL=https://olinloanbot.herokuapp.com
export pageAccessToken=EAAftZCl6HBZCABAJr7vZCjre8w9IvogpoEZC11Dc2ZCg15dwLnPfGUvPkZAHtg0i4FmNZCZAcO45l7VqMYD9u0GutgQOZAsiVxxZBe8OYgQ2s91szQZCH9ZCmEUYAuGENwyA9clahXbk8Qv7DVuNHav8eZA2uAt2yXK0MZBHWpbaZCgC5NmcQZDZD